let Types = [
        ['grass','poison'],
        ['grass', 'poison'],
        ['grass', 'poison'],
        ['fire'],
        ['fire'],
        ['fire', 'flying'],
        ['water'],
        ['water'],
        ['water'],
        ['bug'],
        ['bug'],
        ['bug', 'flying'],
        ['bug', 'poison'],
        ['bug', 'poison'],
        ['bug', 'poison'],
        ['normal','flying'],
        ['normal','flying'],
        ['normal','flying'],
        ['normal'],
        ['normal'],
        ['normal','flying'],
        ['normal','flying'],
        ['poison'],
        ['poison'],
        ['electric'],
        ['electric'],
        ['ground'],
        ['ground'],
        ['poison'],
        ['poison'],
        ['poison', 'ground'],
        ['poison'],
        ['poison'],
        ['poison', 'ground'],
        ['fairy'],
        ['fairy'],
        ['fire'],
        ['fire'],
        ['fairy'],
        ['fairy'],
        ['poison', 'flying'],
        ['poison', 'flying'],
        ['grass', 'poison'],
        ['grass', 'poison'],
        ['grass', 'poison'],
        ['bug', 'grass'],
        ['bug', 'grass'],
        ['bug', 'poison'],
        ['bug', 'poison'],
        ['ground'],
        ['ground'],
        ['normal'],
        ['normal'],
        ['water'],
        ['water'],
        ['fighting'],
        ['fighting'],
        ['fire'],
        ['fire'],
        ['water'],
        ['water'],
        ['water', 'fighting'],
        ['psychic'],
        ['psychic'],
        ['psychic'],
        ['fighting'],
        ['fighting'],
        ['fighting'],
        ['grass', 'poison'],
        ['grass', 'poison'],
        ['grass', 'poison'],
        ['water', 'poison'],
        ['water', 'poison'],
        ['rock', 'ground'],
        ['rock', 'ground'],
        ['rock', 'ground'],
        ['fire'],
        ['fire'],
        ['water', 'psychic'],
        ['water', 'psychic'],
        ['steel', 'electric'],
        ['steel', 'electric'],
        ['normal', 'flying'],
        ['normal', 'flying'],
        ['normal', 'flying'],
        ['water'],
        ['water', 'ice'],
        ['poison'],
        ['poison'],
        ['water', 'ice'],
        ['water', 'ice'],
        ['ghost', 'poison'],
        ['ghost', 'poison'],
        ['ghost', 'poison'],
        ['rock', 'ground'],
        ['psychic'],
        ['psychic'],
        ['water'],
        ['water'],
        ['electric'],
        ['electric'],
        ['grass', 'psychic'],
        ['grass', 'psychic'],
        ['ground'],
        ['ground'],
        ['fighting'],
        ['fighting'],
        ['normal'],
        ['poison'],
        ['poison'],
        ['rock', 'ground'],
        ['rock', 'ground'],
        ['normal'],
        ['grass'],
        ['normal'],
        ['water'],
        ['water'],
        ['normal','water'],
        ['normal','water'],
        ['water', 'psychic'],
        ['water', 'psychic'],
        ['psychic', 'fairy'],
        ['bug', 'flying'],
        ['ice', 'psychic'],
        ['electric'],
        ['fire'],
        ['bug'],
        ['normal'],
        ['water'],
        ['water', 'flying'],
        ['water', 'ice'],
        ['normal'],
        ['normal'],
        ['water'],
        ['electric'],
        ['fire'],
        ['normal'],
        ['water', 'rock'],
        ['water', 'rock'],
        ['water', 'rock'],
        ['water', 'rock'],
        ['rock', 'flying'],
        ['normal'],
        ['flying', 'ice'],
        ['flying', 'electric'],
        ['flying', 'fire'],
        ['dragon'],
        ['dragon'],
        ['dragon', 'flying'],
        ['psychic'],
        ['psychic'],
        ['grass'],
        ['grass'],
        ['grass'],
        ['fire'],
        ['fire'],
        ['fire'],
        ['water'],
        ['water'],
        ['water'],
        ['normal'],
        ['normal'],
        ['normal', 'flying'],
        ['normal', 'flying'],
        ['bug', 'flying'],
        ['bug', 'flying'],
        ['bug', 'poison'],
        ['bug', 'poison'],
        ['poison', 'flying'],
        ['water', 'electric'],
        ['water', 'electric'],
        ['electric'],
        ['fairy'],
        ['fairy'],
        ['fairy'],
        ['fairy', 'flying'],
        ['flying', 'psychic'],
        ['flying', 'psychic'],
        ['electric'],
        ['electric'],
        ['electric'],
        ['grass', 'poison'], 
        ['fairy', 'water'],
        ['fairy', 'water'],
        ['ground'],
        ['water'],
        ['grass', 'flying'],
        ['grass', 'flying'],
        ['grass', 'flying'],
        ['normal'],
        ['grass'],
        ['grass'],
        ['bug', 'flying'],
        ['ground', 'water'],
        ['ground', 'water'],
        ['psychic'],
        ['dark'],
        ['dark', 'flying'],
        ['water', 'psychic'],
        ['ghost'],
        ['psychic'],
        ['psychic'],
        ['normal', 'psychic'],
        ['bug'],
        ['bug', 'steel'],
        ['normal'],
        ['ground', 'poison'],
        ['rock', 'steel'],
        ['fairy'],
        ['fairy'],
        ['water', 'poison'],
        ['bug', 'steel'],
        ['bug', 'rock'],
        ['bug', 'fighting'],
        ['ice', 'dark'],
        ['normal'],
        ['normal'],
        ['fire'],
        ['fire', 'rock'],
        ['ground', 'ice'],
        ['ground', 'ice'],
        ['water', 'rock'],
        ['water'],
        ['water'],
        ['flying', 'ice'],
        ['water', 'flying'],
        ['flying', 'steel'],
        ['fire', 'dark'],
        ['fire', 'dark'],
        ['water', 'dragon'],
        ['ground'],
        ['ground'],
        ['normal'],
        ['normal'],
        ['normal'],
        ['fighting'],
        ['fighting'],
        ['ice', 'psychic'],
        ['electric'],
        ['fire'],
        ['normal'],
        ['normal'],
        ['electric'],
        ['fire'],
        ['water'],
        ['rock', 'ground'],
        ['rock', 'ground'],
        ['rock', 'dark'],
        ['flying', 'psychic'],
        ['fire', 'flying'],
        ['grass', 'psychic'],
        ['grass'],
        ['grass'],
        ['grass'],
        ['fire'],
        ['fire'],
        ['fire', 'fighting'],
        ['water'],
        ['water', 'ground'],
        ['water', 'ground'],
        ['dark'],
        ['dark'],
        ['normal'],
        ['normal'],
        ['bug', 'poison'],
        ['bug', 'poison'],
        ['bug', 'grass'],
        ['bug', 'poison'],
        ['bug', 'poison'],
        ['water', 'grass'],
        ['water', 'grass'],
        ['water', 'grass'],
        ['grass'],
        ['grass', 'dark'],
        ['grass', 'dark'],
        ['normal', 'flying'],
        ['normal', 'flying'],
        ['water', 'flying'],
        ['water', 'flying'],
        ['psychic', 'fairy'],
        ['psychic', 'fairy'],
        ['psychic', 'fairy'],
        ['bug', 'water'],
        ['bug', 'water'],
        ['grass'],
        ['grass', 'fighting'],
        ['normal'],
        ['normal'],
        ['normal'],
        ['bug'],
        ['bug', 'flying'],
        ['bug', 'ghost'],
        ['normal'],
        ['normal'],
        ['normal'],
        ['fighting'],
        ['fighting'],
        ['fairy'],
        ['rock'],
        ['normal'],
        ['normal'],
        ['ghost', 'dark'],
        ['steel', 'fairy'],
        ['steel', 'ground'],
        ['steel', 'ground'],
        ['steel', 'ground'],
        ['psychic', 'fighting'],
        ['psychic', 'fighting'],
        ['electric'],
        ['electric'],
        ['electric'],
        ['electric'],
        ['bug', 'electric'],
        ['bug', 'electric'],
        ['grass', 'poison'],
        ['poison'],
        ['poison'],
        ['water', 'dark'],
        ['water', 'dark'],
        ['water'],
        ['water'],
        ['fire', 'rock'],
        ['fire', 'rock'],
        ['fire'],
        ['psychic'],
        ['psychic'],
        ['normal'],
        ['ground'],
        ['ground', 'dragon'],
        ['ground', 'dragon'],
        ['grass', 'dark'],
        ['grass', 'dark'],
        ['normal','flying'],
        ['flying', 'dragon'],
        ['normal'],
        ['poison'],
        ['rock', 'psychic'],
        ['rock' ,'psychic'],
        ['water', 'ground'],
        ['water', 'ground'],
        ['water'],
        ['water', 'dark'],
        ['ground', 'psychic'],
        ['ground', 'psychic'],
        ['grass', 'rock'],
        ['grass', 'rock'],
        ['bug', 'rock'],
        ['bug', 'rock'],
        ['water'],
        ['water'],
        ['normal'],
        ['normal'],
        ['ghost'],
        ['ghost'],
        ['ghost'],
        ['ghost'],
        ['grass', 'flying'],
        ['psychic'],
        ['dark'],
        ['psychic'],
        ['ice'],
        ['ice'],
        ['water'],
        ['water'],
        ['water', 'ice'],
        ['water'],
        ['water'],
        ['water'],
        ['water', 'rock'],
        ['water'],
        ['dragon'],
        ['dragon'],
        ['dragon', 'flying'],
        ['steel', 'psychic'],
        ['steel', 'psychic'],
        ['steel', 'psychic'],
        ['rock'],
        ['ice'],
        ['steel'],
        ['dragon', 'psychic'],
        ['dragon', 'psychic'],
        ['water'],
        ['ground'],
        ['dragon', 'flying'],
        ['steel', 'psychic'],
        ['psychic'],
        ['grass'],
        ['grass', 'ground'],
        ['grass', 'ground'],
        ['fire'],
        ['fire', 'fighting'],
        ['fire', 'fighting'],
        ['water'],
        ['water', 'steel'],
        ['water', 'steel'],
        ['normal', 'flying'],
        ['normal', 'flying'],
        ['normal', 'flying'],
        ['normal'],
        ['normal', 'water'],
        ['bug'],
        ['bug'],
        ['electric'],
        ['electric'],
        ['electric', 'dark'],
        ['grass', 'poison'],
        ['grass', 'poison'],
        ['rock'],
        ['rock'],
        ['rock', 'steel'],
        ['rock', 'steel'],
        ['grass'],
        ['grass', 'flying'],
        ['grass', 'flying'],
        ['bug', 'flying'],
        ['bug', 'flying'],
        ['electric'],
        ['water'],
        ['water'],
        ['grass'],
        ['grass'],
        ['water', 'ground'],
        ['water', 'ground'],
        ['normal'],
        ['ghost', 'flying'],
        ['ghost', 'flying'],
        ['normal'],
        ['normal', 'fighting'],
        ['ghost'],
        ['flying', 'dark'],
        ['normal'],
        ['normal'],
        ['psychic'],
        ['poison', 'dark'],
        ['poison', 'dark'],
        ['steel', 'psychic'],
        ['steel', 'psychic'],
        ['ground'],
        ['fairy', 'psychic'],
        ['normal'],
        ['normal', 'flying'],
        ['ghost', 'dark'],
        ['dragon'],
        ['dragon', 'ground'],
        ['dragon', 'ground'],
        ['normal'],
        ['fighting'],
        ['fighting', 'steel'],
        ['ground'],
        ['ground'],
        ['poison', 'bug'],
        ['poison', 'bug'],
        ['poison', 'fighting'],
        ['poison', 'fighting'],
        ['grass', 'flying'],
        ['water'],
        ['water'],
        ['water', 'flying'],
        ['ice', 'grass'],
        ['ice', 'grass'],
        ['ice', 'dark'],
        ['steel', 'electric'],
        ['normal'],
        ['rock', 'ground'],
        ['grass'],
        ['electric'],
        ['fire'],
        ['fairy', 'flying'],
        ['bug', 'flying'],
        ['grass'],
        ['ice'],
        ['steel', 'ground'],
        ['ground', 'ice'],
        ['normal'],
        ['fighting', 'psychic'],
        ['steel', 'rock'],
        ['ghost'],
        ['ghost', 'ice'],
        ['ghost', 'electric'],
        ['psychic'],
        ['psychic'],
        ['psychic'],
        ['dragon', 'steel'],
        ['dragon', 'water'],
        ['fire', 'steel'],
        ['normal'],
        ['dragon', 'ghost'],
        ['psychic'],
        ['water', 'psychic'],
        ['water', 'psychic'],
        ['dark'],
        ['grass', 'flying'],
        ['normal'],
        ['fire', 'psychic'],
        ['grass'],
        ['grass'],
        ['grass'],
        ['fire'],
        ['fire'],
        ['fire', 'fighting'],
        ['water'],
        ['water'],
        ['water'],
        ['normal'],
        ['normal'],
        ['normal'],
        ['normal'],
        ['normal'],
        ['dark'],
        ['dark'],
        ['grass'],
        ['grass'],
        ['fire'],
        ['fire'],
        ['water'],
        ['water'],
        ['psychic'],
        ['psychic'],
        ['normal', 'flying'],
        ['normal', 'flying'],
        ['normal', 'flying'],
        ['electric'],
        ['electric'],
        ['rock', 'ground'],
        ['rock', 'ground'],
        ['rock', 'ground'],
        ['flying', 'psychic'],
        ['flying', 'psychic'],
        ['ground'],
        ['ground', 'steel'],
        ['normal'],
        ['fighting'],
        ['fighting'],
        ['fighting'],
        ['water'],
        ['water', 'ground'],
        ['water', 'ground'],
        ['fighting'],
        ['fighting'],
        ['bug', 'grass'],
        ['bug', 'grass'],
        ['bug', 'grass'],
        ['bug', 'poison'],
        ['bug', 'poison'],
        ['bug', 'poison'],
        ['grass', 'fairy'],
        ['grass', 'fairy'],
        ['grass'],
        ['grass'],
        ['water'],
        ['ground'],
        ['ground'],
        ['ground', 'dark'],
        ['fire'],
        ['fire'],
        ['grass'],
        ['bug', 'rock'],
        ['bug', 'rock'],
        ['fighting'],
        ['fighting', 'dark'],
        ['flying', 'psychic'],
        ['ghost', 'dark'],
        ['ghost', 'dark'],
        ['water', 'rock'],
        ['water', 'rock'],
        ['rock', 'flying'],
        ['rock', 'flying'],
        ['poison'],
        ['poison'],
        ['dark'],
        ['dark'],
        ['normal'],
        ['noraml'],
        ['psychic'],
        ['psychic'],
        ['psychic'],
        ['psychic'],
        ['psychic'],
        ['psychic'],
        ['water', 'flying'],
        ['water', 'flying'],
        ['ice'],
        ['ice'],
        ['ice'],
        ['grass'],
        ['grass'],
        ['electric', 'flying'],
        ['bug'],
        ['bug', 'steel'],
        ['grass', 'poison'],
        ['grass', 'poison'],
        ['water', 'ghost'],
        ['water', 'ghost'],
        ['water'],
        ['bug', 'electric'],
        ['bug', 'electric'],
        ['grass', 'steel'],
        ['grass', 'steel'],
        ['steel'],
        ['steel'],
        ['steel'],
        ['electric'],
        ['electric'],
        ['electric'],
        ['psychic'],
        ['psychic'],
        ['fire', 'ghost'],
        ['fire', 'ghost'],
        ['fire', 'ghost'],
        ['dragon'],
        ['dragon'],
        ['dragon'],
        ['ice'],
        ['ice'],
        ['ice'],
        ['bug', 'steel'],
        ['bug'],
        ['ground', 'electric'],
        ['fighting'],
        ['fighting'],
        ['dragon'],
        ['ghost', 'ground'],
        ['ghost', 'ground'],
        ['dark' ,'steel'],
        ['dark', 'steel'],
        ['normal'],
        ['normal', 'flying'],
        ['normal', 'flying'],
        ['dark', 'flying'],
        ['dark', 'flying'],
        ['fire'],
        ['steel', 'bug'],
        ['dark', 'dragon'],
        ['dark', 'dragon'],
        ['dark', 'dragon'],
        ['bug', 'fire'],
        ['bug', 'fire'],
        ['steel', 'fighting'],
        ['rock', 'fighting'],
        ['grass', 'fighting'],
        ['flying'],
        ['flying', 'electric'],
        ['dragon', 'fire'],
        ['dragon', 'electric'],
        ['ground', 'flying'],
        ['dragon' ,'ice'],
        ['water', 'fighting'],
        ['normal', 'psychic'],
        ['bug'],
        ['grass'],
        ['grass'],
        ['grass', 'fighting'],
        ['fire'],
        ['fire'],
        ['fire', 'psychic'],
        ['water'],
        ['water'],
        ['water', 'dark'],
        ['normal'],
        ['normal', 'ground'],
        ['normal', 'flying'],
        ['normal', 'flying'],
        ['fire', 'flying'],
        ['bug'],
        ['bug'],
        ['bug', 'flying'],
        ['fire'],
        ['fire'],
        ['fairy'],
        ['fairy'],
        ['fairy'],
        ['normal', 'grass'],
        ['normal', 'grass'],
        ['fighting'],
        ['fighting', 'dark'],
        ['normal'],
        ['psychic'],
        ['psychic'],
        ['steel', 'ghost'],
        ['steel', 'ghost'],
        ['steel', 'ghost'],
        ['fairy'],
        ['fairy'],
        ['fairy'],
        ['fairy'],
        ['psychic', 'dark'],
        ['psychic', 'dark'],
        ['rock', 'water'],
        ['rock', 'water'],
        ['water', 'poison'],
        ['water', 'dragon'],
        ['water'],
        ['water'],
        ['normal', 'electric'],
        ['normal', 'electric'],
        ['rock'],
        ['rock', 'dragon'],
        ['rock', 'ice'],
        ['rock', 'ice'],
        ['fairy'],
        ['fighting', 'flying'],
        ['fairy', 'electric'],
        ['fairy', 'rock'],
        ['dragon'],
        ['dragon'],
        ['dragon'],
        ['steel', 'fairy'],
        ['ghost', 'grass'],
        ['ghost', 'grass'],
        ['ghost', 'grass'],
        ['ghost', 'grass'],
        ['ice'],
        ['ice'],
        ['flying', 'dragon'],
        ['flying', 'dragon'],
        ['fairy'],
        ['dark', 'flying'],
        ['dragon', 'ground'],
        ['rock', 'fairy'],
        ['psychic', 'ghost'],
        ['water', 'fire'],
        ['grass', 'flying'],
        ['grass', 'flying'],
        ['grass', 'ghost'],
        ['fire'],
        ['fire'],
        ['fire', 'dark'],
        ['water'],
        ['water'],
        ['water', 'fairy'],
        ['normal', 'flying'],
        ['normal', 'flying'],
        ['normal', 'flying'],
        ['normal'],
        ['normal'],
        ['bug'],
        ['bug', 'electric'],
        ['bug', 'electric'],
        ['water', 'fighting'],
        ['ice', 'fighting'],
        ['fire', 'flying'],
        ['bug', 'fairy'],
        ['bug', 'fairy'],
        ['rock'],
        ['rock'],
        ['water'],
        ['water', 'poison'],
        ['water', 'poison'],
        ['ground'],
        ['ground'],
        ['bug', 'water'],
        ['bug', 'water'],
        ['grass'],
        ['grass'],
        ['grass', 'fairy'],
        ['grass', 'fairy'],
        ['poison', 'fire'],
        ['poison', 'fire'],
        ['normal', 'fighting'],
        ['normal', 'fighting'],
        ['grass'],
        ['grass'],
        ['grass'],
        ['grass', 'fairy'],
        ['normal', 'psychic'],
        ['normal', 'fighting'],
        ['bug', 'water'],
        ['bug', 'water'],
        ['ground', 'ghost'],
        ['ground', 'ghost'],
        ['water'],
        ['normal'],
        ['normal'],
        ['rock'],
        ['normal'],
        ['fire', 'dragon'],
        ['rock', 'electric'],
        ['ghost', 'fairy'],
        ['water'],
        ['normal', 'dragon'],
        ['ghost', 'grass'],
        ['dragon'],
        ['dragon', 'fighting'],
        ['dragon', 'fighting'],
        ['electric', 'fairy'],
        ['psychic', 'fairy'],
        ['grass', 'fairy'],
        ['water', 'fairy'],
        ['psychic'],
        ['psychic'],
        ['psychic', 'steel'],
        ['psychic', 'ghost'],
        ['rock', 'poison'],
        ['bug', 'fighting'],
        ['bug', 'fighting'],
        ['electric'],
        ['steel', 'flying'],
        ['grass', 'steel'],
        ['dark', 'dragon'],
        ['psychic'],
        ['steel', 'fairy'],
        ['fighting', 'ghost'],
        ['poison'],
        ['poison', 'dragon'],
        ['rock', 'steel'],
        ['fire', 'ghost'],
        ['electric'],
    ];
    
    export default Types;